"""empty message

Revision ID: 43ee4498ee8e
Revises: 5d6c69731f5b
Create Date: 2019-11-11 14:57:05.942087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ee4498ee8e'
down_revision = '5d6c69731f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'active')
    # ### end Alembic commands ###
