"""empty message

Revision ID: 5d6c69731f5b
Revises: 
Create Date: 2019-11-10 23:22:18.084676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d6c69731f5b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team_name', sa.String(length=50), nullable=True))
    op.alter_column('player', 'image_url',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    op.alter_column('player', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('player', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('player', 'image_url',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('player', 'team_name')
    # ### end Alembic commands ###
