"""empty message

Revision ID: 9ab38c3d1034
Revises: 3ab13fe04df2
Create Date: 2019-11-16 18:58:21.029137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ab38c3d1034'
down_revision = '3ab13fe04df2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('team_user_fkey', 'team', type_='foreignkey')
    op.create_foreign_key(None, 'team', 'user', ['user_id'], ['id'])
    op.drop_column('team', 'user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'team', type_='foreignkey')
    op.create_foreign_key('team_user_fkey', 'team', 'user', ['user'], ['id'])
    op.drop_column('team', 'user_id')
    # ### end Alembic commands ###
